name: swift_chat
description: A capstone project for Ada Developers Academy where users can make quick and simple visual communication boards.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  google_fonts: ^1.1.0
  flutter_boom_menu: ^1.0.2
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  modal_progress_hud: ^0.1.3
  flutter_tts: ^1.2.6
  transparent_image: ^1.0.0
  url_launcher: ^5.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/